url: https://y7kim.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: Colin But Solutions
email: colin.but1@hotmail.co.uk
description: "Colin But Solutions Company Website - delivering first class Software Consultancy Services focusing on DevOps & Application Development"


# Team names, titles and social links
people:
- name: Colin But
  pic: me_fb
  position: Lead DevOps Engineer
  social:
    - title: twitter
      url: https://twitter.com/Colin_But
    - title: facebook
      url: https://www.facebook.com/colin.but
    - title: github
      url: https://github.com/colinbut/

- name: Colin But
  pic: me_linkedin
  position: Founder & Director
  social:
    - title: twitter
      url: https://twitter.com/Colin_But
    - title: facebook
      url: https://www.facebook.com/colin.but
    - title: linkedin
      url: https://www.linkedin.com/in/colinbut/

- name: Colin But
  pic: me3
  position: Software Developer
  social:
    - title: twitter
      url: https://twitter.com/Colin_But
    - title: facebook
      url: https://www.facebook.com/colin.but
    - title: github
      url: https://github.com/colinbut/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Flat 123, My House
  - line: London, UK

# Build settings
markdown: kramdown
permalink: pretty